name: workflow_02
on: 
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          repository: 'trucnguyentps/Testing'
          token: ${{ secrets.GH_PAT }}
          ref: main